package convenience_store;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 * Term Project COSC 457 Section: 101
 * GROUP B MEMBERS: Benjamin King, Angina Shrestha, Alvin Kim, Daniella Diaz
 * Project Name: At Your Convenience 
 * Purpose: Convenience Store Inventory System
 * Due Date: November 23, 2020
 */
public class Receipt extends javax.swing.JFrame {

    /*
    Below is a method to print the receipt of the user.
    It will display information such as product type, price, quantity, and total number of items.
    This can be printed to a printer or printed on the screen.
    */
    public Receipt() {
        initComponents();
    }
    String lsub;
    String lpay;
    String lbal;
    
    public Receipt(String sub, String pay, String bal, TableModel tableModel) throws PrinterException {
        initComponents();
        this.lsub = sub;
        this.lpay = pay;
        this.lbal = bal;
        
        txtprint.setText(txtprint.getText() + "---------------RECEIPT TOP---------------\n");
        txtprint.setText(txtprint.getText() + "Store: At Your Convenience \n");
        txtprint.setText(txtprint.getText() + "Location: Towson, MD. \n");
        txtprint.setText(txtprint.getText() + "Below you can find a summary of your purchases today. \n");
        txtprint.setText(txtprint.getText() + "WARNING: Without a receipt you will not qualify for a refund. \n");


        txtprint.setText(txtprint.getText() + "\n");
        //This for loop traverse through the table to grab the information we need to display to the user on the receipt.
        for (int i = 0; i < tableModel.getRowCount(); i++){
            String product = (String) tableModel.getValueAt(i, 1);
            String price = (String) tableModel.getValueAt(i, 2);
            String quant =  (String) tableModel.getValueAt(i, 3);
            int total = (int) tableModel.getValueAt(i, 4);
            txtprint.setText(txtprint.getText() + "Product Type: "+ product + "\t" + "Price: "+ price + "\t"+ "Quantity: " + quant + "\t" + "Total: " + total + "\n");
            
        }
        txtprint.setText(txtprint.getText() + "\n");
        txtprint.setText(txtprint.getText() + "Your Total: " + sub + "\n");   
        txtprint.setText(txtprint.getText() + "Amount Paid: " + pay + "\n");
        txtprint.setText(txtprint.getText() + "Amount left: " + bal + "\n");
        txtprint.setText(txtprint.getText() + "---------------RECEIPT BOTTOM---------------\n");
        txtprint.print();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtprint.setColumns(20);
        txtprint.setRows(5);
        jScrollPane1.setViewportView(txtprint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtprint;
    // End of variables declaration//GEN-END:variables
}
